name: 'Upload release.nix'
description: 'Upload a Nix lock file for releases'
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ${{ github.action_path }}/release.sh
