name: 'Upload release.nix'
description: 'Upload a Nix lock file for releases'
outputs:
  asset_path:
    description: "Filename of release.nix lock file"
    value: ${{ steps.create-release-nix.outputs.asset_path }}
runs:
  using: 'composite'
  steps:
    - id: create-release-nix
      shell: bash
      run: |
        asset_path="$(mktemp "release-XXXXXXXXXX.nix")"
        ${{ github.action_path }}/release.sh \
          "https://github.com/${{ github.repository }}" \
          "$GITHUB_SHA" \
          > "$asset_path"
        echo "::set-output name=asset_path::$(echo $asset_path)"
